### ISSUE TITLE
Quit event i zatvaranje modalnog prozora

### ISSUE THREAD

**Issue by vasiljevic** [Petlja/pygame4skulpt#2]
Kada se klikne za zatvaranje modalnog prozora (dugme Close ili klik na pozadinu) tada treba samo da se generiše QUIT event Pygame-u, a samo zatvaranje modalnog prozora treba da radi pg.quit().

Drugim rečima, ako bismo imali samo imali da se nešto nacrta i na kraju:

```python
pg.display.update()
pg.time.wait(5000)
pg.quit()
```
onda bi program trebao radio ovako: otvori se modalni prozor u kome je nešto nacrtano, korisnik ako klikće (na Close, na background) ništa se ne dešava i na kraju posle 5 sekundi se modalni prozor zatvori.

**Comment by denkoRa** [comment]
Delimicno se slazem, samo sto ovde moze biti problema kada dete zaboravi pg.quit() u kodu, a to je jedina opcija da se iskljuci modal. Naravno moze da se refreshuje strana, ali koliko njih se odmah toga seti?
S druge strane mi bi trebalo da im uvek obezbedimo boiler plate kod sa pg.quit() na kraju..

**Comment by vasiljevic** [comment]
ako se zaboravi, onda i na desktopu ostane zamrznuto, pa mora da se na silu
gasi.

Nebojša Vasiljević

2018-06-18 13:00 GMT+02:00 Radenko Pavlovic <notifications@github.com>:

**Comment by delta003** [comment]
Python-like resenje bi bilo varijanta context menadzera (https://docs.python.org/2.5/whatsnew/pep-343.html):
```
with pygame(....) as pg:
     # do work
```
Ali ne znam da li skulpt uopste podrzava `with` i da li bi autori uopste hteli da upoznaju decu sa with (verovatno ne).

**Comment by vasiljevic** [comment]
nisam to video u pygame primerima nigde. Pošto je ovo deincijalizacija modula, mogao bi da ima neku deinicijalizaciju na onexit, ali tu pygame nije baš utegao.

**Comment by vasiljevic** [comment]
@denkoRa Evo gde se u activecode.js čisti nakon izvršavanja programa:
https://github.com/Petlja/RunestoneComponents-Petlja/blob/ee17bd84d66558c9e2b0d72add763e805a4f100a/runestone/activecode/js/activecode.js#L1065

Samo treba da vidiš kako elegantno da prepoznaš na tom mesto da je ostao otvoren modalni prozor i da ga onda počistiš
