### ISSUE TITLE
Surface

### ISSUE THREAD

**Issue by filipmaric** [Petlja/pygame4skulpt#21]
Dodati mogućnost da se crta na posebnom Surface objektu koji se nakon toga blituje na prozor (pogledati primer spirograph.py u Pygame priručniku koji trenutno ne radi.

**Comment by milenkoviclazar** [comment]
Primer spirograph.py proradi kada se u linijama 13 i 14 konstanta 2/3 zameni sa 0.67. Ovo je zato što Skulpt prat Python 2 sintaksu.
Drugi fiks je da se u 39. liniji stavi alpha kanal boje na nešto što nije nula. Nisam siguran zašto se ovo ponaša drugačije kada je alpha stavljen na 0. Istražiću još.
