### ISSUE TITLE
Plan to next step?

### ISSUE THREAD

**Issue by alexwenbj** [Petlja/pygame4skulpt#35]
It is a nice job!But it still have many things to do from completion.Do you have a plan to complete it?Especially the Sprite class,it is the core class of PyGame.
Thank you for your great job again.

**Comment by vasiljevic** [comment]
@alexwenbj you're welcome. 

We have developed features in the areas we need for our educational materials (like https://petlja.org/biblioteka/r/lekcije/pygame-prirucnik-gim/animacije-animacijeviseobjekata, there will be an English version in the autumn). 

Currently, our lessons do not cover Sprite class. As usual, contributions are welcome :)

**Comment by alexwenbj** [comment]
@vasiljevic Yeah,I saw it,but can't understand it cause it is in Serbian :-)
